### PR TITLE
Journal week 6 to master

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by jeffworley** [comment]
solid start on all three.  looking forward to your witty reflective. :+1:

**Comment by ericquayson** [comment]
looks good :+1: ill be using your media queries tutorial as a reference

**Comment by ShayHall** [comment]
:+1: Looks like solid bones for putting meat on later this week.  :meat_on_bone:

**Comment by jeremyrist** [comment]
Yeah I'm right there with you haha :+1:

**Comment by jeffworley** [comment]
Solid work on all three.  You have gotten even better at being concise yet still informative.  I am impressed.  :+1:

**Comment by rosalsm** [comment]
Very well done, very organize and clearly explained :+1:  Tutorial week 6 instead of 5

**Comment by s4dmw** [comment]
good catch!

**Comment by jeremyrist** [comment]
:+1: Awesome tutorial Dave, thanks for that

**Pull request merged**
