### PR TITLE
Update creative-tutorial-title-week-4.md

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by ericksonk** [comment]
Very descriptive and easy to follow, nice work :+1:

**Comment by drumslayert** [comment]
Nicely done node-sasser! :+1:

**Comment by jeffworley** [comment]
Very clear and to the point.  Only thing I would consider in retrospect would be to mention the idea of --global installation so that the new user would be less likely to run into issues. :+1:

**Comment by s4dmw** [comment]
ah, good catch...thanks!

**Pull request merged**
