### PR TITLE
Week 3 to master

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by ericksonk** [comment]
Take a second look at the beginning of your first sentence in your journal, there's one too many "topic"'s in there. Looks good besides that

Very helpful and thorough tutorial on browser-sync :+1:

**Comment by jeffworley** [comment]
Looks great!  I like how you have filled out the solid outline you started with and it is very easy to read and understand. :+1:

**Comment by jeremyrist** [comment]
"More commonly known by its street name: CSS" hahaha GTFO :+1: 

I loved your summary on `media-queries` and `Responsive Web Design`. I haven't been able to wrap my mind around `@media` _YET_ so I might need to talk to you about that...fun writing style tho!

**Comment by jeremyrist** [comment]
Dang man, you had me all ready to buy some browser-sync and then you dropped the FREE bomb on 'em! :+1:  haha but where's the sock??

**Pull request merged**
