### PR TITLE
Journal and Tutorial week 4 to master

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by jeffworley** [comment]
Got some choice topics to choose from breh! :sunglasses:  I really hope that you will choose to elaborate on your chessboard solution for the reflective and teach us how to jQuery better in your tut! :+1:

**Comment by ShayHall** [comment]
Good list of topics.  I'll check back in to get some tutoring in jQUERY  :heavy_dollar_sign: :+1:

**Comment by drumslayert** [comment]
Good job on the start os your journal Dave! :+1:

**Comment by drumslayert** [comment]
Im anxious to see what topic you pick for your tutorial. Great choices! :+1:

**Comment by jeremyrist** [comment]
:+1: .addClass() and .removeClass() would be a good one :+1:

**Pull request merged**
