### PR TITLE
Journal week 7

### PR DESCRIPTION
**Pull request by s4dmw**

### CODE REVIEW

**Comment by ShayHall** [comment]
:+1: Good work so far on all of them.  Relevant tutorial and resource topics and the review of our group project was spot on.

**Comment by Ricecoder** [comment]
Good work! Your resource was in fact super duper. :+1:

**Comment by Ricecoder** [comment]
Keep up the good work! :+1:

**Comment by ShayHall** [comment]
Still looking good.  :+1:

**Pull request merged**
